# Práctica 1.1 — Probabilidad y Estadística 
## Actividad 1 — Identificación de la fuente
### Análisis de la evolución poblacional anual

**CIta**
> UN, World Population Prospects (2024) – processed by Our World in Data. “Annual change in population – UN WPP” [dataset]. United Nations, “World Population Prospects”; United Nations, “World Population Prospects - Interim Update” [original data]. 

**Preguntas** 

Responde brevemente: 

1. ¿Quién produjo originalmente los datos? United Nations

2. ¿Qué organización los procesa para su utilización en Our World in Data? Our World in Data

3. ¿Qué representa la variable que analizarás? Annual population growth

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("C:\\5TO SEMESTRE PROYECTOS\\TÓPICOS DE BIG DATA\\UI_1_Probabiidad_estadistica\\data\\raw\\annual-population-growth\\annual-population-growth.csv")
df

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN
...,...,...,...,...,...
38395,Zimbabwe,ZWE,2096,NaN,100752.0
38396,Zimbabwe,ZWE,2097,NaN,91796.0
38397,Zimbabwe,ZWE,2098,NaN,87605.0
38398,Zimbabwe,ZWE,2099,NaN,76670.0
38399,Zimbabwe,ZWE,2100,NaN,70019.0

In [5]:
df.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [6]:
df.shape

(38400, 5)

In [7]:
df.columns.tolist()

['Entity',
 'Code',
 'Year',
 'Annual change in population',
 'Annual population change (Projected)']

In [8]:

df.dtypes

Entity                                      str
Code                                        str
Year                                      int64
Annual change in population             float64
Annual population change (Projected)    float64
dtype: object

In [9]:
df.describe()

,Year,Annual change in population,Annual population change (Projected)
count,38400.000000,1.868800e+04,1.971200e+04
mean,2025.500000,2.063019e+06,8.375481e+05
std,43.300872,9.440859e+06,5.816745e+06
min,1951.000000,-3.315935e+06,-2.291035e+07
25%,1988.000000,1.781000e+03,-9.742750e+03
50%,2025.500000,4.689800e+04,9.350000e+01
75%,2063.000000,3.021128e+05,1.411160e+05
max,2100.000000,9.337137e+07,7.206736e+07

In [10]:
df.isnull().sum()

Entity                                      0
Code                                     1200
Year                                        0
Annual change in population             19712
Annual population change (Projected)    18688
dtype: int64

In [11]:
df["Entity"].nunique()

256

In [12]:
df_exxtraccion_entity = df[["Entity", "Year"]]
df_exxtraccion_entity.shape
# df_exxtraccion_entity.head(3)

(38400, 2)

In [13]:
df_2020 = df[df["Year"] == 2020]
df_2020.head(3)

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
69,Afghanistan,AFG,2020,1212852.0,NaN
219,Africa (UN),UN_AFR,2020,32815675.0,NaN
369,Albania,ALB,2020,-13061.0,NaN

In [14]:
df_2020_ext_col1 = df_2020[["Entity", "Year"]]
df_2020_ext_col1.head(3)
df_2020_ext_col2 = df[df["Year"] == 2020][["Entity", "Year"]]
df_2020_ext_col2.head(3)

          Entity  Year
69   Afghanistan  2020
219  Africa (UN)  2020
369      Albania  2020

In [15]:
df_2005_2020 = df[(df["Year"] >= 2005) & (df["Year"] <= 2020) & (df["Entity"] == "Mexico")]
df_2005_2020.shape

(16, 5)

In [16]:
df_2005_2020.head(3)

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22254,Mexico,MEX,2005,1417373.0,NaN
22255,Mexico,MEX,2006,1442162.0,NaN
22256,Mexico,MEX,2007,1520690.0,NaN

In [17]:
df_ext_EA = df_2005_2020[["Entity", "Annual change in population"]]
df_ext_EA.head(3)

       Entity  Annual change in population
22254  Mexico                    1417373.0
22255  Mexico                    1442162.0
22256  Mexico                    1520690.0

In [18]:
dfC = df[df["Entity"].str.startswith("C")]
dfCPaises = dfC["Entity"].unique()
dfCPaises

<StringArray>
[                'Cambodia',                 'Cameroon',
                   'Canada',               'Cape Verde',
           'Cayman Islands', 'Central African Republic',
                     'Chad',                    'Chile',
                    'China',                 'Colombia',
                  'Comoros',                    'Congo',
             'Cook Islands',               'Costa Rica',
            'Cote d'Ivoire',                  'Croatia',
                     'Cuba',                  'Curacao',
                   'Cyprus',                  'Czechia']
Length: 20, dtype: str

In [19]:
dfFiltroC = df[(df["Entity"] == "China") & (df["Year"] >= 1983) & (df["Year"] <= 2021)]
dfFiltroC

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
6782,China,CHN,1983,15476775.0,NaN
6783,China,CHN,1984,14784693.0,NaN
6784,China,CHN,1985,15958173.0,NaN
6785,China,CHN,1986,17425789.0,NaN
6786,China,CHN,1987,18983838.0,NaN
6787,China,CHN,1988,19026723.0,NaN
6788,China,CHN,1989,18746838.0,NaN
6789,China,CHN,1990,19591719.0,NaN
6790,China,CHN,1991,17205808.0,NaN
6791,China,CHN,1992,13785703.0,NaN
6792,China,CHN,1993,12734338.0,NaN
6793,China,CHN,1994,11694525.0,NaN
6794,China,CHN,1995,11130830.0,NaN
6795,China,CHN,1996,10810880.0,NaN
6796,China,CHN,1997,10194814.0,NaN
6797,China,CHN,1998,9707499.0,NaN
6798,China,CHN,1999,9329528.0,NaN
6799,China,CHN,2000,9404524.0,NaN
6800,China,CHN,2001,9143887.0,NaN
6801,China,CHN,2002,8141774.0,NaN
6802,China,CHN,2003,7650488.0,NaN
6803,China,CHN,2004,7582993.0,NaN
6804,China,CHN,2005,7926819.0,NaN
6805,China,CHN,2006,8026895.0,NaN
6806,China,CHN,2007,7759546.0,NaN
6807,China,CHN,2008,8007435.0,NaN
6808,China,CHN,2009,8701706.0,NaN
6809,China,CHN,2010,9038788.0,NaN
6810,China,CHN,2011,8689153.0,NaN
6811,China,CHN,2012,9270208.0,NaN
6812,China,CHN,2013,9487174.0,NaN
6813,China,CHN,2014,8943930.0,NaN
6814,China,CHN,2015,8182201.0,NaN
6815,China,CHN,2016,7918457.0,NaN
6816,China,CHN,2017,8302102.0,NaN
6817,China,CHN,2018,6654224.0,NaN
6818,China,CHN,2019,4511403.0,NaN
6819,China,CHN,2020,2585736.0,NaN
6820,China,CHN,2021,331176.0,NaN

In [20]:
dfFiltroC.mean(numeric_only=True)

Year                                    2.002000e+03
Annual change in population             1.058587e+07
Annual population change (Projected)             NaN
dtype: float64

In [21]:
dfFiltroC.median(numeric_only=True)

Year                                       2002.0
Annual change in population             9270208.0
Annual population change (Projected)          NaN
dtype: float64

In [22]:
dfFiltroC.var(numeric_only=True)

Year                                    1.300000e+02
Annual change in population             2.051512e+13
Annual population change (Projected)             NaN
dtype: float64

In [23]:
dfFiltroC.std(numeric_only=True)

Year                                    1.140175e+01
Annual change in population             4.529362e+06
Annual population change (Projected)             NaN
dtype: float64

In [24]:
dfFiltroC.min(numeric_only=True)

Year                                      1983.0
Annual change in population             331176.0
Annual population change (Projected)         NaN
dtype: float64

In [25]:
dfFiltroC.max(numeric_only=True)

Year                                        2021.0
Annual change in population             19591719.0
Annual population change (Projected)           NaN
dtype: float64

In [26]:
df.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [36]:
df.loc[:, "Entity"]

0        Afghanistan
1        Afghanistan
2        Afghanistan
3        Afghanistan
4        Afghanistan
            ...
38395       Zimbabwe
38396       Zimbabwe
38397       Zimbabwe
38398       Zimbabwe
38399       Zimbabwe
Name: Entity, Length: 38400, dtype: str

In [49]:
df.iloc[:, [0,2]]

            Entity  Year
0      Afghanistan  1951
1      Afghanistan  1952
2      Afghanistan  1953
3      Afghanistan  1954
4      Afghanistan  1955
...            ...   ...
38395     Zimbabwe  2096
38396     Zimbabwe  2097
38397     Zimbabwe  2098
38398     Zimbabwe  2099
38399     Zimbabwe  2100

[38400 rows x 2 columns]

In [47]:
df.iloc[600:610, 0:2]

             Entity Code
600  American Samoa  ASM
601  American Samoa  ASM
602  American Samoa  ASM
603  American Samoa  ASM
604  American Samoa  ASM
605  American Samoa  ASM
606  American Samoa  ASM
607  American Samoa  ASM
608  American Samoa  ASM
609  American Samoa  ASM

# Ejercicios loc iloc

In [52]:
df.loc[10000]

Entity                                  Equatorial Guinea
Code                                                  GNQ
Year                                                 2051
Annual change in population                           NaN
Annual population change (Projected)              46407.0
Name: 10000, dtype: object

In [53]:
df.iloc[10000]

Entity                                  Equatorial Guinea
Code                                                  GNQ
Year                                                 2051
Annual change in population                           NaN
Annual population change (Projected)              46407.0
Name: 10000, dtype: object

In [57]:
df.loc[:, ["Entity", "Year", "Annual change in population"]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [58]:
df.iloc[:, [0,2,3]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [59]:
df.loc[10000, ["Entity", "Year", "Annual change in population"]]

Entity                         Equatorial Guinea
Year                                        2051
Annual change in population                  NaN
Name: 10000, dtype: object

In [61]:
df.iloc[10000, [0, 2, 3]]

Entity                         Equatorial Guinea
Year                                        2051
Annual change in population                  NaN
Name: 10000, dtype: object

In [ ]:
df.loc[(df["Year"] == 2020) & (df["Entity"] == "Mexico")]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22269,Mexico,MEX,2020,1036075.0,NaN

In [ ]:
df.iloc[]