In [39]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [2]:
df.head(10)

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975
5  Afghanistan  AFG  1955            30.3660
6  Afghanistan  AFG  1956            30.8303
7  Afghanistan  AFG  1957            31.3451
8  Afghanistan  AFG  1958            31.8400
9  Afghanistan  AFG  1959            32.3365

In [ ]:
df.rename(columns={
    "entity": "Pais",
    "code": "codigo",
    "year": "año",
    "life_expectancy_0": "esperanzaVida"
    }, inplace=True)

In [28]:
df.head(10)

                 code  life_expectancy_0
entity      year
Afghanistan 1950  AFG            28.1563
            1951  AFG            28.5836
            1952  AFG            29.0138
            1953  AFG            29.4521
            1954  AFG            29.6975
            1955  AFG            30.3660
            1956  AFG            30.8303
            1957  AFG            31.3451
            1958  AFG            31.8400
            1959  AFG            32.3365

In [22]:
df.set_index("Pais", inplace=True)

In [27]:
df.set_index(["entity", "year"], inplace=True)

In [33]:
df.loc[df["entity"].str.contains("UNI", case=False, regex=True)]

                             entity code  year  life_expectancy_0
15803                       Reunion  REU  1950            47.5602
15804                       Reunion  REU  1951            48.6476
15805                       Reunion  REU  1952            50.1082
15806                       Reunion  REU  1953            51.4650
15807                       Reunion  REU  1954            52.9912
...                             ...  ...   ...                ...
20581  United States Virgin Islands  VIR  2019            74.8761
20582  United States Virgin Islands  VIR  2020            74.7137
20583  United States Virgin Islands  VIR  2021            74.6132
20584  United States Virgin Islands  VIR  2022            75.0449
20585  United States Virgin Islands  VIR  2023            75.4724

[666 rows x 4 columns]

In [35]:
df.dropna(subset=["code"], inplace=True)
df.isnull().sum()

entity               0
code                 0
year                 0
life_expectancy_0    0
dtype: int64

In [41]:
df.head()

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [ ]:
resultado = (
    df.groupby("entity")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)

In [44]:
resultado.head(5)

entity
USSR            32.700000
South Sudan     37.841631
Sierra Leone    43.189605
Mali            43.760793
Niger           44.187513
Name: life_expectancy_0, dtype: float64

In [45]:
df_2020 = df[df["year"] == 2020]

In [46]:
df_2020.head(5)

             entity      code  year  life_expectancy_0
70      Afghanistan       AFG  2020            61.4537
146          Africa  OWID_AFR  2020            62.2572
220         Albania       ALB  2020            77.8241
297         Algeria       DZA  2020            73.2568
371  American Samoa       ASM  2020            72.6717

In [51]:
resultado_2020 = (
    df_2020.groupby("entity")["life_expectancy_0"]
    .min()
    .sort_values(ascending=True)
)

In [52]:
resultado_2020.head(5)

entity
Central African Republic    50.5959
Nigeria                     53.0724
Chad                        53.0818
Lesotho                     55.1325
Somalia                     57.0948
Name: life_expectancy_0, dtype: float64